title: Atomic Tomorrow Adventures
description: Adventures in Yesterday's Tomorrow!
theme: minima
baseurl: "/atomic-tomorrow-adventures" # the subpath of your site
url: "https://majyc.github.io" # the base hostname & protocol for your site

# Build settings
markdown: kramdown
permalink: /:categories/:title/
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-archives
  - jekyll-redirect-from
  - jekyll-gist
  - jekyll-remote-theme

# Exclude these files from the build
exclude:
  - code/*
  - node_modules/
  - "*/node_modules/"
  - package.json
  - package-lock.json
  - README.md
  - Gemfile
  - Gemfile.lock
  - .gitignore
  - vendor/
# Collections for organizing content
collections:
  rules:
    output: true
    permalink: /rules/:path/
  setting:
    output: true
    permalink: /setting/:path/

# Default layouts
defaults:
  - scope:
      path: "rules"
      type: "pages"
    values:
      layout: default
  - scope:
      path: "setting"
      type: "pages"
    values:
      layout: default